### ISSUE TITLE
Issue in rendering html page?

### ISSUE THREAD

**Issue by gatemezing** [cfoster/xmllondon-rdf#23]
I've just tried this link http://data.semanticweb.org/conference/xmllondon/2015/paper/labella and the HTML rendering seems to have some issues to be rendered.

**Comment by cfoster** [comment]
E-Mailed Islam @mogaio who I believe is now responsible for data.semanticweb.org inserts, with the latest updates/corrections to the dataset - which should hopefully fix this issue. I will update this ticket with any kind of response.

New RDF/XML files for [data.semanticweb.org](http://data.semanticweb.org) at:

[xmllondon-complete-2013.rdf](https://github.com/cfoster/xmllondon-rdf/blob/master/data.semanticweb.org/xmllondon-complete-2013.rdf)
[xmllondon-complete-2014.rdf](https://github.com/cfoster/xmllondon-rdf/blob/master/data.semanticweb.org/xmllondon-complete-2014.rdf)
[xmllondon-complete-2015.rdf](https://github.com/cfoster/xmllondon-rdf/blob/master/data.semanticweb.org/xmllondon-complete-2015.rdf)

**Comment by cfoster** [comment]
I presently plan to migrate XML London data URIs will to scholarlydata w3id URIs.

Some data has already been Migrated thanks to @anuzzolese and @AnLiGentile, however, I will migrate the rest and it will be in this format going forward.

The URL you use at the start of this ticket will convert to:

http://www.scholarlydata.org/inproceedings/xmllondon2015/paper/labella
